sudo: required
services:
  -docker

before_install: 
  - docker build -t regulagadda/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true regulagadda/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-new"
  env: "Docker-new-env"
  bucket_name: "elasticbeanstalk-us-east-1-445963195352"
  bucket_path: "docker-new"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"